-- 3. 用量统计表 (高频更新)
create table public.usages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  feature_key text not null, -- e.g., 'ai_generations'
  count int default 0,
  updated_at timestamptz default now(),
  unique(user_id, feature_key)
);